/**
 * fieldCatalog.js — Catálogo central de campos para o módulo de relatórios.
 * Cada campo define: id, label, key (accessor), origem, tipo, modulo,
 * visivelPadrao, exportavel, filtravel, agrupavel, largura, alinhamento, formato, ordem.
 *
 * "key" pode ser string (prop direta) ou função (row) => valor.
 */

// ── Helpers de formato ─────────────────────────────────────────────────────
export const FORMATTERS = {
  "data-br": (v) => {
    if (!v) return "";
    // yyyy-mm-dd → dd/mm/yyyy
    const m = String(v).match(/^(\d{4})-(\d{2})-(\d{2})/);
    return m ? `${m[3]}/${m[2]}/${m[1]}` : v;
  },
  "datetime-br": (v) => {
    if (!v) return "";
    const m = String(v).match(/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2})/);
    return m ? `${m[3]}/${m[2]}/${m[1]} ${m[4]}:${m[5]}` : v;
  },
  "moeda": (v) => {
    const n = parseFloat(String(v).replace(",", "."));
    if (isNaN(n)) return v || "";
    return n.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
  },
  "texto": (v) => String(v ?? ""),
  "upper": (v) => String(v ?? "").toUpperCase(),
  "numero": (v) => {
    const n = parseFloat(String(v).replace(",", "."));
    return isNaN(n) ? "" : String(n);
  },
};

export function applyFormat(field, value) {
  const fmt = FORMATTERS[field.formato] || FORMATTERS["texto"];
  return fmt(value);
}

export function getFieldValue(field, row) {
  if (typeof field.key === "function") return field.key(row);
  return row[field.key] ?? "";
}

// ── Catálogo completo ──────────────────────────────────────────────────────
export const FIELD_CATALOG = [
  // ── Módulo: Planilha (dados principais — Supabase) ─────────────────────
  {
    id: "dt",
    label: "DT",
    key: "dt",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: true,
    exportavel: true,
    filtravel: true,
    agrupavel: false,
    largura: 80,
    alinhamento: "center",
    formato: "texto",
    ordem: 1,
  },
  {
    id: "nome",
    label: "Motorista",
    key: "nome",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: true,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 160,
    alinhamento: "left",
    formato: "texto",
    ordem: 2,
  },
  {
    id: "cpf",
    label: "CPF",
    key: "cpf",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 120,
    alinhamento: "center",
    formato: "texto",
    ordem: 3,
  },
  {
    id: "placa",
    label: "Placa",
    key: "placa",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: true,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 90,
    alinhamento: "center",
    formato: "upper",
    ordem: 4,
  },
  {
    id: "placa2",
    label: "Placa 2",
    key: "placa2",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 90,
    alinhamento: "center",
    formato: "upper",
    ordem: 5,
  },
  {
    id: "placa3",
    label: "Placa 3",
    key: "placa3",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 90,
    alinhamento: "center",
    formato: "upper",
    ordem: 6,
  },
  {
    id: "vinculo",
    label: "Vínculo",
    key: "vinculo",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 100,
    alinhamento: "center",
    formato: "texto",
    ordem: 7,
  },
  {
    id: "origem",
    label: "Origem",
    key: "origem",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: true,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 120,
    alinhamento: "left",
    formato: "texto",
    ordem: 8,
  },
  {
    id: "destino",
    label: "Destino",
    key: "destino",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: true,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 120,
    alinhamento: "left",
    formato: "texto",
    ordem: 9,
  },
  {
    id: "status",
    label: "Status",
    key: "status",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: true,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 120,
    alinhamento: "center",
    formato: "texto",
    ordem: 10,
  },
  {
    id: "data_carr",
    label: "Data Carregamento",
    key: "data_carr",
    origem: "supabase",
    tipo: "data",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: false,
    largura: 110,
    alinhamento: "center",
    formato: "data-br",
    ordem: 11,
  },
  {
    id: "data_agenda",
    label: "Data Agenda",
    key: "data_agenda",
    origem: "supabase",
    tipo: "data",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: true,
    exportavel: true,
    filtravel: true,
    agrupavel: false,
    largura: 110,
    alinhamento: "center",
    formato: "data-br",
    ordem: 12,
  },
  {
    id: "data_desc",
    label: "Data Descarga",
    key: "data_desc",
    origem: "supabase",
    tipo: "data",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: true,
    exportavel: true,
    filtravel: true,
    agrupavel: false,
    largura: 110,
    alinhamento: "center",
    formato: "data-br",
    ordem: 13,
  },
  {
    id: "dias",
    label: "Dias",
    key: "dias",
    origem: "supabase",
    tipo: "numero",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 60,
    alinhamento: "center",
    formato: "numero",
    ordem: 14,
  },
  {
    id: "cliente",
    label: "Cliente",
    key: "cliente",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 140,
    alinhamento: "left",
    formato: "texto",
    ordem: 15,
  },
  {
    id: "vl_cte",
    label: "Valor CTE",
    key: "vl_cte",
    origem: "supabase",
    tipo: "moeda",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 110,
    alinhamento: "right",
    formato: "moeda",
    ordem: 16,
  },
  {
    id: "vl_contrato",
    label: "Valor Contrato",
    key: "vl_contrato",
    origem: "supabase",
    tipo: "moeda",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 120,
    alinhamento: "right",
    formato: "moeda",
    ordem: 17,
  },
  {
    id: "adiant",
    label: "Adiantamento",
    key: "adiant",
    origem: "supabase",
    tipo: "moeda",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 110,
    alinhamento: "right",
    formato: "moeda",
    ordem: 18,
  },
  {
    id: "saldo",
    label: "Saldo",
    key: "saldo",
    origem: "supabase",
    tipo: "moeda",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 100,
    alinhamento: "right",
    formato: "moeda",
    ordem: 19,
  },
  {
    id: "diaria_prev",
    label: "Diária Prevista",
    key: "diaria_prev",
    origem: "supabase",
    tipo: "moeda",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 110,
    alinhamento: "right",
    formato: "moeda",
    ordem: 20,
  },
  {
    id: "diaria_pg",
    label: "Diária Paga",
    key: "diaria_pg",
    origem: "supabase",
    tipo: "moeda",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 100,
    alinhamento: "right",
    formato: "moeda",
    ordem: 21,
  },
  {
    id: "cte",
    label: "CTE",
    key: "cte",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: false,
    largura: 80,
    alinhamento: "center",
    formato: "texto",
    ordem: 22,
  },
  {
    id: "mdf",
    label: "MDF-e",
    key: "mdf",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 80,
    alinhamento: "center",
    formato: "texto",
    ordem: 23,
  },
  {
    id: "nf",
    label: "NF",
    key: "nf",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 80,
    alinhamento: "center",
    formato: "texto",
    ordem: 24,
  },
  {
    id: "mat",
    label: "MAT",
    key: "mat",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 80,
    alinhamento: "center",
    formato: "texto",
    ordem: 25,
  },
  {
    id: "ro",
    label: "RO",
    key: "ro",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 80,
    alinhamento: "center",
    formato: "texto",
    ordem: 26,
  },
  {
    id: "chegada",
    label: "Chegada",
    key: "chegada",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 90,
    alinhamento: "center",
    formato: "texto",
    ordem: 27,
  },
  {
    id: "obs",
    label: "Observação",
    key: "obs",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 200,
    alinhamento: "left",
    formato: "texto",
    ordem: 28,
  },
  {
    id: "sinistro",
    label: "Sinistro",
    key: "sinistro",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: false,
    largura: 100,
    alinhamento: "center",
    formato: "texto",
    ordem: 29,
  },
  {
    id: "gerenc",
    label: "Gerenciamento",
    key: "gerenc",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 120,
    alinhamento: "left",
    formato: "texto",
    ordem: 30,
  },
  {
    id: "sgs",
    label: "SGS",
    key: "sgs",
    origem: "supabase",
    tipo: "texto",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 80,
    alinhamento: "center",
    formato: "texto",
    ordem: 31,
  },
  {
    id: "updated_at",
    label: "Última Atualização",
    key: "updated_at",
    origem: "supabase",
    tipo: "datetime",
    modulo: "planilha",
    moduloLabel: "Planilha",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 140,
    alinhamento: "center",
    formato: "datetime-br",
    ordem: 32,
  },

  // ── Módulo: Diárias (calculados a partir de dados principais) ──────────
  {
    id: "diaria_status",
    label: "Status Diária",
    key: (row) => {
      const da = row.data_agenda, dd = row.data_desc, ch = row.chegada;
      if (!da) return "";
      const agenda = new Date(da + "T00:00:00");
      const desc = dd ? new Date(dd + "T00:00:00") : null;
      if (desc) {
        return diffDiasSimples(agenda, desc) > 0 ? "Com Diária" : "Sem Diária";
      }
      if (ch) return "Aguardando Descarga";
      return "Pendente";
    },
    origem: "calculado",
    tipo: "texto",
    modulo: "diarias",
    moduloLabel: "Diárias",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 120,
    alinhamento: "center",
    formato: "texto",
    ordem: 40,
  },
  {
    id: "dias_atraso",
    label: "Dias em Trânsito",
    key: (row) => {
      const da = row.data_agenda, dd = row.data_desc;
      if (!da) return "";
      const agenda = new Date(da + "T00:00:00");
      const fim = dd ? new Date(dd + "T00:00:00") : new Date();
      fim.setHours(0, 0, 0, 0);
      const diff = Math.round((fim - agenda) / 86400000);
      return diff > 0 ? String(diff) : "0";
    },
    origem: "calculado",
    tipo: "numero",
    modulo: "diarias",
    moduloLabel: "Diárias",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 100,
    alinhamento: "center",
    formato: "numero",
    ordem: 41,
  },

  // ── Módulo: Apontamentos ───────────────────────────────────────────────
  {
    id: "apt_numero",
    label: "Apt. Número",
    key: "numero",
    origem: "apontamentos",
    tipo: "texto",
    modulo: "apontamentos",
    moduloLabel: "Apontamentos",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 90,
    alinhamento: "center",
    formato: "texto",
    ordem: 50,
  },
  {
    id: "apt_mes_ref",
    label: "Apt. Mês Ref.",
    key: "mes_ref",
    origem: "apontamentos",
    tipo: "texto",
    modulo: "apontamentos",
    moduloLabel: "Apontamentos",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 90,
    alinhamento: "center",
    formato: "texto",
    ordem: 51,
  },
  {
    id: "apt_filial",
    label: "Apt. Filial",
    key: "filial",
    origem: "apontamentos",
    tipo: "texto",
    modulo: "apontamentos",
    moduloLabel: "Apontamentos",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 100,
    alinhamento: "left",
    formato: "texto",
    ordem: 52,
  },
  {
    id: "apt_tipo",
    label: "Apt. Tipo",
    key: "tipo",
    origem: "apontamentos",
    tipo: "texto",
    modulo: "apontamentos",
    moduloLabel: "Apontamentos",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 120,
    alinhamento: "left",
    formato: "texto",
    ordem: 53,
  },
  {
    id: "apt_valor",
    label: "Apt. Valor",
    key: "valor",
    origem: "apontamentos",
    tipo: "moeda",
    modulo: "apontamentos",
    moduloLabel: "Apontamentos",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 100,
    alinhamento: "right",
    formato: "moeda",
    ordem: 54,
  },
  {
    id: "apt_descricao",
    label: "Apt. Descrição",
    key: "descricao_apontamento",
    origem: "apontamentos",
    tipo: "texto",
    modulo: "apontamentos",
    moduloLabel: "Apontamentos",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 200,
    alinhamento: "left",
    formato: "texto",
    ordem: 55,
  },
  {
    id: "apt_frs_folha",
    label: "Apt. FRS/Folha",
    key: "frs_folha",
    origem: "apontamentos",
    tipo: "texto",
    modulo: "apontamentos",
    moduloLabel: "Apontamentos",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 100,
    alinhamento: "center",
    formato: "texto",
    ordem: 56,
  },
  {
    id: "apt_dt_rel",
    label: "Apt. DT Rel.",
    key: "dt_rel",
    origem: "apontamentos",
    tipo: "texto",
    modulo: "apontamentos",
    moduloLabel: "Apontamentos",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 80,
    alinhamento: "center",
    formato: "texto",
    ordem: 57,
  },

  // ── Módulo: SGS ────────────────────────────────────────────────────────
  {
    id: "sgs_numero",
    label: "SGS Número",
    key: "numero",
    origem: "sgs",
    tipo: "texto",
    modulo: "sgs",
    moduloLabel: "SGS",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 90,
    alinhamento: "center",
    formato: "texto",
    ordem: 60,
  },
  {
    id: "sgs_data_chamado",
    label: "SGS Data Chamado",
    key: "data_chamado",
    origem: "sgs",
    tipo: "data",
    modulo: "sgs",
    moduloLabel: "SGS",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: false,
    largura: 120,
    alinhamento: "center",
    formato: "data-br",
    ordem: 61,
  },
  {
    id: "sgs_ultimo_retorno",
    label: "SGS Último Retorno",
    key: "ultimo_retorno",
    origem: "sgs",
    tipo: "data",
    modulo: "sgs",
    moduloLabel: "SGS",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 130,
    alinhamento: "center",
    formato: "data-br",
    ordem: 62,
  },
  {
    id: "sgs_status",
    label: "SGS Status",
    key: "status",
    origem: "sgs",
    tipo: "texto",
    modulo: "sgs",
    moduloLabel: "SGS",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 100,
    alinhamento: "center",
    formato: "texto",
    ordem: 63,
  },
  {
    id: "sgs_descricao",
    label: "SGS Descrição",
    key: "descricao",
    origem: "sgs",
    tipo: "texto",
    modulo: "sgs",
    moduloLabel: "SGS",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 200,
    alinhamento: "left",
    formato: "texto",
    ordem: 64,
  },

  // ── Módulo: Motoristas ─────────────────────────────────────────────────
  {
    id: "mot_nome",
    label: "Motorista (cadastro)",
    key: "nome",
    origem: "motoristas",
    tipo: "texto",
    modulo: "motoristas",
    moduloLabel: "Motoristas",
    visivelPadrao: false,
    exportavel: true,
    filtravel: true,
    agrupavel: true,
    largura: 160,
    alinhamento: "left",
    formato: "texto",
    ordem: 70,
  },
  {
    id: "mot_cpf",
    label: "CPF (cadastro)",
    key: "cpf",
    origem: "motoristas",
    tipo: "texto",
    modulo: "motoristas",
    moduloLabel: "Motoristas",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 120,
    alinhamento: "center",
    formato: "texto",
    ordem: 71,
  },
  {
    id: "mot_tel",
    label: "Telefone",
    key: "tel",
    origem: "motoristas",
    tipo: "texto",
    modulo: "motoristas",
    moduloLabel: "Motoristas",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 120,
    alinhamento: "center",
    formato: "texto",
    ordem: 72,
  },
  {
    id: "mot_placa",
    label: "Placa (cadastro)",
    key: "placa",
    origem: "motoristas",
    tipo: "texto",
    modulo: "motoristas",
    moduloLabel: "Motoristas",
    visivelPadrao: false,
    exportavel: true,
    filtravel: false,
    agrupavel: false,
    largura: 90,
    alinhamento: "center",
    formato: "upper",
    ordem: 73,
  },
];

// ── Função auxiliar interna (cálculo de dias sem dependência externa) ──────
function diffDiasSimples(d1, d2) {
  return Math.round((d2 - d1) / 86400000);
}

// ── Grupos de campos por módulo ────────────────────────────────────────────
export const FIELD_GROUPS = [
  { modulo: "planilha",     label: "Planilha (Supabase)" },
  { modulo: "diarias",      label: "Diárias (Calculados)" },
  { modulo: "apontamentos", label: "Apontamentos" },
  { modulo: "sgs",          label: "SGS" },
  { modulo: "motoristas",   label: "Motoristas" },
];

// ── Campos visíveis por padrão ─────────────────────────────────────────────
export const DEFAULT_VISIBLE = FIELD_CATALOG
  .filter((f) => f.visivelPadrao)
  .map((f) => f.id);

// ── Status válidos (para filtros) ──────────────────────────────────────────
export const STATUS_OPCOES = [
  "CARREGADO", "PENDENTE", "NO-SHOW", "NÃO ACEITE", "EM ABERTO", "CANCELADO",
];
