-- =============================================
-- Migration 068: km medido dos 278 trechos de Belem e Imperatriz
-- =============================================
-- Fecha o que a migration 066 deixou em aberto: o relatorio do TMS dessas duas pracas veio
-- com 230 das 298 distancias ZERADAS e outras erradas por ordem de grandeza. Aqui entra a
-- distancia rodoviaria medida (Nominatim + OSRM), em `km_calc`, sem tocar no `km` do TMS.
--
-- COMO A CIDADE FOI IDENTIFICADA (o ponto delicado): o TMS trunca o destino em 20
-- caracteres e nao informa UF, entao "DAVINOPOLIS" tanto e MA quanto GO. A primeira
-- rodada, sem UF, roteou IMP/NNO para Davinopolis-GO e devolveu 1.669 km -- o certo sao
-- 17 km, e nesse caso o TMS (13 km) estava mais perto que o calculo. A rodada definitiva
-- resolve a UF ANTES de geocodificar, nesta ordem:
--   1. UF que a propria operacao registra nas viagens (controle_operacional.destino traz
--      "DAVINOPOLIS-MA" 197 vezes) -- 140 trechos;
--   2. municipio unico com aquele nome na lista do IBGE -- 138 trechos;
--   3. sem criterio -> NAO grava numero. Chute silencioso aqui viraria km errado em
--      relatorio de conciliacao.
-- `destino_resolvido` guarda a cidade escolhida com UF, para conferir depois.
--
-- CONFERENCIA: onde o TMS tinha numero plausivel, 50 dos 66 batem dentro de 10%
-- (Imperatriz->Sao Luis: 630 medido x 633 do TMS). As divergencias fortes que sobraram sao
-- do lado do TMS: IMP/OLI Olinda 17.136 -> 1.740; IMP/PDI Pedreiras 4.682 -> 467;
-- BEM/SLU Sao Luis 1 -> 788; IMP/DRD Dourados 120 -> 2.473.
--
-- FORA DO LOTE de proposito: BEM/BEM e IMP/IMP (origem = destino) -- o roteador devolve 0
-- e o km urbano do TMS (20 e 24) e mais util que zero.

UPDATE trechos t SET km_calc = v.km, km_calc_fonte = 'osrm',
                     destino_resolvido = v.res, km_calc_em = now()
FROM (VALUES
  ('BEMAAZ',395,'Santa Luzia do Parua - MA'),
  ('BEMABU',19,'Marituba - PA'),
  ('BEMACJ',2016,'Aracaju - SE'),
  ('BEMACL',503,'Acailandia - MA'),
  ('BEMACT',2634,'Aracatuba - SP'),
  ('BEMADR',3253,'Angra dos Reis - RJ'),
  ('BEMAEP',2804,'Campos Gerais - MG'),
  ('BEMAGA',816,'Araguaina - TO'),
  ('BEMAHD',2108,'Alhandra - PB'),
  ('BEMALG',1988,'Alagoinhas - BA'),
  ('BEMALV',2933,'Nova Alvorada do Sul - MS'),
  ('BEMANN',13,'Ananindeua - PA'),
  ('BEMANP',1920,'Anapolis - GO'),
  ('BEMASL',1986,'Santo Amaro - BA'),
  ('BEMATI',2842,'Atibaia - SP'),
  ('BEMBAI',1632,'Barreiras - BA'),
  ('BEMBAL',958,'Balsas - MA'),
  ('BEMBCS',1908,'Bom Conselho - PE'),
  ('BEMBEH',2645,'Belo Horizonte - MG'),
  ('BEMBET',2654,'Betim - MG'),
  ('BEMBGB',1111,'Baixa Grande do Ribeiro - PI'),
  ('BEMBNV',29,'Benevides - PA'),
  ('BEMBRA',1941,'Brasilia - DF'),
  ('BEMBRG',2844,'Braganca Paulista - SP'),
  ('BEMBRI',2865,'Barueri - SP'),
  ('BEMBTS',2593,'Batatais - SP'),
  ('BEMCAS',3678,'Caxias do Sul - RS'),
  ('BEMCBA',2370,'Cuiaba - MT'),
  ('BEMCCC',2982,'Cariacica - ES'),
  ('BEMCCG',210,'Braganca - PA'),
  ('BEMCGA',113,'Igarape-Acu - PA'),
  ('BEMCJM',2839,'Cajamar - SP'),
  ('BEMCLO',2076,'Cabedelo - PB'),
  ('BEMCLT',921,'Colinas do Tocantins - TO'),
  ('BEMCLU',2151,'Cacule - BA'),
  ('BEMCMC',2034,'Camacari - BA'),
  ('BEMCSG',2037,'Cabo de Santo Agostinho - PE'),
  ('BEMCST',71,'Castanhal - PA'),
  ('BEMCTG',2636,'Contagem - MG'),
  ('BEMCUC',1473,'Caucaia - CE'),
  ('BEMDEL',1798,'Delmiro Gouveia - AL'),
  ('BEMDID',650,'Palestina do Para - PA'),
  ('BEMDSS',3861,'Dois Irmaos - RS'),
  ('BEMDUC',3260,'Duque de Caxias - RJ'),
  ('BEMEEU',116,'Abaetetuba - PA'),
  ('BEMFEO',1334,'Confresa - MT'),
  ('BEMFGR',2045,'Cristalina - GO'),
  ('BEMFOR',1496,'Fortaleza - CE'),
  ('BEMFSN',1936,'Feira de Santana - BA'),
  ('BEMGGO',1042,'Sao Felix do Xingu - PA'),
  ('BEMGON',1978,'Goiania - GO'),
  ('BEMGRP',1345,'Gurupi - TO'),
  ('BEMGUA',2880,'Guarulhos - SP'),
  ('BEMIJA',3418,'Itajai - SC'),
  ('BEMIMD',172,'Mae do Rio - PA'),
  ('BEMIMP',570,'Imperatriz - MA'),
  ('BEMIPO',2036,'Ipojuca - PE'),
  ('BEMJBR',2030,'Jaboatao dos Guararapes - PE'),
  ('BEMJDD',441,'Jacunda - PA'),
  ('BEMJIP',2726,'Ji-Parana - RO'),
  ('BEMJIR',2264,'Jaciara - MT'),
  ('BEMJPA',2055,'Joao Pessoa - PB'),
  ('BEMJRI',2916,'Jacarei - SP'),
  ('BEMJTI',2300,'Jatai - GO'),
  ('BEMJUD',2817,'Jundiai - SP'),
  ('BEMJUZ',1544,'Juazeiro - BA'),
  ('BEMLOD',2890,'Londrina - PR'),
  ('BEMLOU',2802,'Louveira - SP'),
  ('BEMMAB',550,'Maraba - PA'),
  ('BEMMAC',1493,'Maracanau - CE'),
  ('BEMMEO',2038,'Maceio - AL'),
  ('BEMMNU',1935,'Inhumas - GO'),
  ('BEMMUA',2896,'Maua - SP'),
  ('BEMMUS',3044,'Manaus - AM'),
  ('BEMNAT',2094,'Natal - RN'),
  ('BEMNDO',514,'Rondon do Para - PA'),
  ('BEMNER',1925,'Neropolis - GO'),
  ('BEMNNO',586,'Davinopolis - MA'),
  ('BEMNTO',3658,'Santo Cristo - RS'),
  ('BEMOCI',211,'Capitao Poco - PA'),
  ('BEMOHN',2012,'Nossa Senhora do Socorro - SE'),
  ('BEMOSD',700,'Sao Geraldo do Araguaia - PA'),
  ('BEMPGN',282,'Paragominas - PA'),
  ('BEMPIL',1995,'Pilar - AL'),
  ('BEMPLL',2614,'Pedro Leopoldo - MG'),
  ('BEMPLM',1190,'Palmas - TO'),
  ('BEMPLT',2042,'Paulista - PE'),
  ('BEMPNI',2769,'Paulinia - SP'),
  ('BEMPON',1248,'Porto Nacional - TO'),
  ('BEMPPL',211,'Salinopolis - PA'),
  ('BEMPRP',2762,'Presidente Prudente - SP'),
  ('BEMPRT',1169,'Paraiso do Tocantins - TO'),
  ('BEMPRV',2561,'Porto Velho - RO'),
  ('BEMQKA',683,'Anapu - PA'),
  ('BEMREC',2027,'Recife - PE'),
  ('BEMRED',894,'Redencao - PA'),
  ('BEMREF',2757,'Regente Feijo - SP'),
  ('BEMRJN',3280,'Rio de Janeiro - RJ'),
  ('BEMRNA',894,'Redencao - PA'),
  ('BEMRPO',2567,'Ribeirao Preto - SP'),
  ('BEMSAB',1793,'Sao Bento - PB'),
  ('BEMSAV',2051,'Salvador - BA'),
  ('BEMSLU',788,'Sao Luis - MA'),
  ('BEMSMF',2025,'Simoes Filho - BA'),
  ('BEMSPO',2870,'Sao Paulo - SP'),
  ('BEMSRT',1221,'Santarem - PA'),
  ('BEMSTN',541,'Santa Ines - MA'),
  ('BEMSUR',2761,'Sumare - SP'),
  ('BEMSZP',42,'Santa Izabel do Para - PA'),
  ('BEMTHE',903,'Teresina - PI'),
  ('BEMTLI',260,'Tailandia - PA'),
  ('BEMTUC',978,'Tucuma - PA'),
  ('BEMUAO',991,'Conceicao do Araguaia - PA'),
  ('BEMUBA',2783,'Bataguassu - MS'),
  ('BEMUBE',2328,'Uberlandia - MG'),
  ('BEMUPE',712,'Parauapebas - PA'),
  ('BEMVIN',2878,'Varginha - MG'),
  ('BEMVSI',349,'Viseu - PA'),
  ('BEMXIN',783,'Xinguara - PA'),
  ('BEMZED',477,'Ze Doca - MA'),
  ('IMP000',1109,'Luis Eduardo Magalhaes - BA'),
  ('IMPAAS',2180,'Araras - SP'),
  ('IMPACJ',1720,'Aracaju - SE'),
  ('IMPACL',68,'Acailandia - MA'),
  ('IMPAGA',247,'Araguaina - TO'),
  ('IMPAGM',1598,'Agua Limpa - GO'),
  ('IMPALA',1333,'Aguas Lindas de Goias - GO'),
  ('IMPALG',1692,'Alagoinhas - BA'),
  ('IMPALT',655,'Altos - PI'),
  ('IMPANP',1351,'Anapolis - GO'),
  ('IMPAPG',1424,'Aparecida de Goiania - GO'),
  ('IMPAPR',1689,'Arapiraca - AL'),
  ('IMPAQU',1225,'Aquiraz - CE'),
  ('IMPARU',1603,'Caruaru - PE'),
  ('IMPATF',1617,'Alta Floresta - MT'),
  ('IMPBAC',484,'Bacabal - MA'),
  ('IMPBAI',1063,'Barreiras - BA'),
  ('IMPBAL',389,'Balsas - MA'),
  ('IMPBAX',1752,'Bayeux - PB'),
  ('IMPBCA',571,'Barcarena - PA'),
  ('IMPBEL',571,'Belem - PA'),
  ('IMPBEM',571,'Belem - PA'),
  ('IMPBJM',1552,'Belo Jardim - PE'),
  ('IMPBRA',1372,'Brasilia - DF'),
  ('IMPBRU',1623,'Brumado - BA'),
  ('IMPCAG',1730,'Camaragibe - PE'),
  ('IMPCAJ',1339,'Cajazeiras - PB'),
  ('IMPCAX',578,'Caxias - MA'),
  ('IMPCBA',2061,'Cuiaba - MT'),
  ('IMPCET',2333,'Itaquaquecetuba - SP'),
  ('IMPCGD',1641,'Campina Grande - PB'),
  ('IMPCHA',668,'Chapadinha - MA'),
  ('IMPCMC',1739,'Camacari - BA'),
  ('IMPCMG',2251,'Campo Grande - MS'),
  ('IMPCNV',1571,'Caldas Novas - GO'),
  ('IMPCOJ',1669,'Conceicao do Jacuipe - BA'),
  ('IMPCRL',3614,'Cruzeiro do Sul - AC'),
  ('IMPCRP',1737,'Carpina - PE'),
  ('IMPCSG',1741,'Cabo de Santo Agostinho - PE'),
  ('IMPCTG',2067,'Contagem - MG'),
  ('IMPCUC',1183,'Caucaia - CE'),
  ('IMPDDE',1226,'Carmo do Rio Verde - GO'),
  ('IMPDIV',2324,'Divinopolis - MG'),
  ('IMPDRD',2473,'Dourados - MS'),
  ('IMPEOJ',1991,'Sao Joao de Iracema - SP'),
  ('IMPESS',1783,'Espirito Santo - RN'),
  ('IMPETL',3181,'Estrela - RS'),
  ('IMPEUN',2079,'Eunapolis - BA'),
  ('IMPFOR',1206,'Fortaleza - CE'),
  ('IMPFSN',1641,'Feira de Santana - BA'),
  ('IMPGAB',3177,'Garibaldi - RS'),
  ('IMPGJU',192,'Grajau - MA'),
  ('IMPGMI',2797,'Guajara-Mirim - RO'),
  ('IMPGOM',1215,'Goianesia - GO'),
  ('IMPGON',1410,'Goiania - GO'),
  ('IMPGRP',776,'Gurupi - TO'),
  ('IMPGUA',2311,'Guarulhos - SP'),
  ('IMPHGN',433,'Graca Aranha - MA'),
  ('IMPIAO',2051,'Ribeirao das Neves - MG'),
  ('IMPIBE',1739,'Itambe - PE'),
  ('IMPICO',1253,'Ico - CE'),
  ('IMPIER',2254,'Ipero - SP'),
  ('IMPIGU',1753,'Igarassu - PE'),
  ('IMPILH',1989,'Ilheus - BA'),
  ('IMPIRC',1355,'Irece - BA'),
  ('IMPITN',1961,'Itabuna - BA'),
  ('IMPJBR',1735,'Jaboatao dos Guararapes - PE'),
  ('IMPJCB',1508,'Jacobina - BA'),
  ('IMPJDN',436,'Canaa dos Carajas - PA'),
  ('IMPJPA',1760,'Joao Pessoa - PB'),
  ('IMPJTI',1731,'Jatai - GO'),
  ('IMPJUA',1196,'Juazeiro do Norte - CE'),
  ('IMPJUZ',1249,'Juazeiro - BA'),
  ('IMPLDF',1750,'Lauro de Freitas - BA'),
  ('IMPLDV',1769,'Lucas do Rio Verde - MT'),
  ('IMPLEV',2183,'Joao Monlevade - MG'),
  ('IMPLJS',1710,'Laranjeiras - SE'),
  ('IMPMAB',229,'Maraba - PA'),
  ('IMPMAC',1203,'Maracanau - CE'),
  ('IMPMCB',1779,'Macaiba - RN'),
  ('IMPMDM',77,'Campestre do Maranhao - MA'),
  ('IMPMEO',1742,'Maceio - AL'),
  ('IMPMMS',1423,'Formosa - GO'),
  ('IMPMOR',1709,'Moreno - PE'),
  ('IMPMOS',1433,'Mossoro - RN'),
  ('IMPMSJ',1735,'Mata de Sao Joao - BA'),
  ('IMPMUS',2956,'Manaus - AM'),
  ('IMPNAT',1799,'Natal - RN'),
  ('IMPNER',1356,'Neropolis - GO'),
  ('IMPNNO',17,'Davinopolis - MA'),
  ('IMPNOG',1380,'Novo Gama - GO'),
  ('IMPNRE',766,'Barreirinhas - MA'),
  ('IMPOHN',1717,'Nossa Senhora do Socorro - SE'),
  ('IMPOIN',459,'Santo Antonio dos Lopes - MA'),
  ('IMPOLI',1740,'Olinda - PE'),
  ('IMPOOI',607,'Timon - MA'),
  ('IMPORR',608,'Ourilandia do Norte - PA'),
  ('IMPOTO',1361,'Santo Antonio do Descoberto - GO'),
  ('IMPPAL',1677,'Palmares - PE'),
  ('IMPPAM',1793,'Parnamirim - RN'),
  ('IMPPAR',948,'Parnaiba - PI'),
  ('IMPPBN',2672,'Pimenta Bueno - RO'),
  ('IMPPCS',920,'Picos - PI'),
  ('IMPPDI',467,'Pedreiras - MA'),
  ('IMPPGN',304,'Paragominas - PA'),
  ('IMPPIN',559,'Pinheiro - MA'),
  ('IMPPLA',1248,'Petrolina - PE'),
  ('IMPPLL',2045,'Pedro Leopoldo - MG'),
  ('IMPPLM',621,'Palmas - TO'),
  ('IMPPLT',1747,'Paulista - PE'),
  ('IMPPNP',2029,'Penapolis - SP'),
  ('IMPPNT',1401,'Planaltina - GO'),
  ('IMPPRT',601,'Paraiso do Tocantins - TO'),
  ('IMPPRV',2474,'Porto Velho - RO'),
  ('IMPPSQ',1521,'Pesqueira - PE'),
  ('IMPPTO',1508,'Patos - PB'),
  ('IMPPTS',2141,'Porto Seguro - BA'),
  ('IMPPVL',1827,'Primavera do Leste - MT'),
  ('IMPQYZ',1567,'Garanhuns - PE'),
  ('IMPRBR',2982,'Rio Branco - AC'),
  ('IMPRCI',222,'Buriticupu - MA'),
  ('IMPREC',1732,'Recife - PE'),
  ('IMPRFN',1375,'Senhor do Bonfim - BA'),
  ('IMPRNA',571,'Redencao - PA'),
  ('IMPRNO',1931,'Rondonopolis - MT'),
  ('IMPROS',579,'Rosario - MA'),
  ('IMPRSS',3422,'Rosario do Sul - RS'),
  ('IMPRUS',1307,'Russas - CE'),
  ('IMPRVD',1642,'Rio Verde - GO'),
  ('IMPSAJ',1858,'Santa Juliana - MG'),
  ('IMPSAV',1755,'Salvador - BA'),
  ('IMPSHA',1321,'Serra Talhada - PE'),
  ('IMPSII',1707,'Sorriso - MT'),
  ('IMPSIN',1587,'Sinop - MT'),
  ('IMPSJB',645,'Sao Jose de Ribamar - MA'),
  ('IMPSJU',1790,'Sao Jose de Mipibu - RN'),
  ('IMPSLU',630,'Sao Luis - MA'),
  ('IMPSMF',1729,'Simoes Filho - BA'),
  ('IMPSMM',450,'Sao Miguel do Guama - PA'),
  ('IMPSST',1748,'Santa Rita - PB'),
  ('IMPSTJ',1718,'Santo Antonio de Jesus - BA'),
  ('IMPSTN',384,'Santa Ines - MA'),
  ('IMPSUR',2192,'Sumare - SP'),
  ('IMPSZP',549,'Santa Izabel do Para - PA'),
  ('IMPTAH',2541,'Cachoeiro de Itapemirim - ES'),
  ('IMPTET',1626,'Turvelandia - GO'),
  ('IMPTGS',2299,'Tangara da Serra - MT'),
  ('IMPTHE',616,'Teresina - PI'),
  ('IMPTUM',1613,'Itumbiara - GO'),
  ('IMPUAN',1377,'Anicuns - GO'),
  ('IMPUFF',1404,'Luziania - GO'),
  ('IMPULN',205,'Ulianopolis - PA'),
  ('IMPUPE',388,'Parauapebas - PA'),
  ('IMPVLD',1382,'Valparaiso de Goias - GO'),
  ('IMPVLH',2490,'Vilhena - RO'),
  ('IMPVTC',1759,'Vitoria da Conquista - BA'),
  ('IMPVZG',2066,'Varzea Grande - MT'),
  ('IMPXIN',460,'Xinguara - PA')
) AS v(codigo, km, res) WHERE t.codigo = v.codigo;

-- PENDENTES (18): cidade homonima sem criterio para decidir. Ficam sem km ate o Yves
-- dizer qual e -- na conferencia isso hoje afeta 12 linhas de 3.629.
--   BEMBRN  BARAUNA                ambiguo: Baraúna/RN, Baraúna/PB
--   BEMBVS  BOA VISTA              ambiguo: Boa Vista/RR, Boa Vista/PB
--   BEMCDE  CONDE                  ambiguo: Conde/PB, Conde/BA
--   BEMCNE  CANDEIAS               ambiguo: Candeias/BA, Candeias/MG
--   BEMCPY  CAPANEMA               ambiguo: Capanema/PA, Capanema/PR
--   BEMDOU  DOURADINA              ambiguo: Douradina/PR, Douradina/MS
--   BEMHID  HIDROLANDIA            ambiguo: Hidrolândia/CE, Hidrolândia/GO
--   BEMITB  ITABAIANA              ambiguo: Itabaiana/PB, Itabaiana/SE
--   BEMVLA  VALENCA                ambiguo: Valença/BA, Valença/RJ
--   IMPBRN  BARAUNA                ambiguo: Baraúna/RN, Baraúna/PB
--   IMPBVS  BOA VISTA              ambiguo: Boa Vista/RR, Boa Vista/PB
--   IMPCDE  CONDE                  ambiguo: Conde/PB, Conde/BA
--   IMPFTA  FLORESTA               ambiguo: Floresta/PE, Floresta/PR
--   IMPIGT  IGUATU                 ambiguo: Iguatu/CE, Iguatu/PR
--   IMPIIL  COLINAS                ambiguo: Colinas/MA, Colinas/RS
--   IMPITB  ITABAIANA              ambiguo: Itabaiana/PB, Itabaiana/SE
--   IMPOGC  SAO GONCALO DO AMARA   ambiguo: São Gonçalo do Amarante/CE, São Gonçalo do Amarante/RN
--   IMPVLA  VALENCA                ambiguo: Valença/BA, Valença/RJ
