-- =============================================
-- Migration 069: km medido das 399 rotas de Acailandia (tudo na mesma regua)
-- =============================================
-- Pedido do Yves: as tres pracas com a distancia medida do mesmo jeito, em vez de ACL ficar
-- so com o numero do TMS enquanto BEM/IMP usam o calculado.
--
-- ACHADO: aqui o TMS acertou. Das 402 rotas medidas, 325 batem dentro de 10% do que o
-- relatorio de Acailandia ja dizia (ACL/AGA Araguaina: 314 medido = 314 do TMS). Nada a ver
-- com Belem e Imperatriz, onde 230 de 298 vinham zeradas. Mesmo assim o TMS continua em
-- `km` e o medido em `km_calc` -- a regra de nao sobrescrever a fonte vale igual.
--
-- CORRIGIDO A MAO na revisao (o casamento automatico errou):
--   ACL/ACU  "ACU" casou por prefixo com Acucena/MG; e Assu/RN (1.570 km, TMS dizia 1.468)
--   ACL/299  "OLHO DAGUA DAS FLORE" -> Olho d'Agua das Flores/AL (o apostrofo quebrou)
--   ACL/MJZ  "MOJI DAS CRUZES" -> Mogi das Cruzes/SP (grafia antiga no TMS)
--   ACL/SZP  "SANTA ISABEL DO PARA" -> Santa Izabel do Para/PA (IBGE grafa com Z)
--
-- FORA DO LOTE: ACL/ACL (origem = destino, o roteador da 0 e o km urbano do TMS e melhor)
-- e 5 casos em que o km do TMS aponta para OUTRA cidade homonima -- decidir no chute ali
-- seria pior que deixar em branco.

UPDATE trechos t SET km_calc = v.km, km_calc_fonte = 'osrm',
                     destino_resolvido = v.res, km_calc_em = now()
FROM (VALUES
  ('ACL000',1176,'Luis Eduardo Magalhaes - BA'),
  ('ACL254',2296,'Pains - MG'),
  ('ACL299',1656,'Olho d''Agua das Flores - AL'),
  ('ACL312',1229,'Itaituba - PA'),
  ('ACL365',2193,'Itabirito - MG'),
  ('ACLA01',2837,'Itapoa - SC'),
  ('ACLACJ',1787,'Aracaju - SE'),
  ('ACLACT',2133,'Aracatuba - SP'),
  ('ACLACU',1570,'Assu - RN'),
  ('ACLADF',1278,'Ceres - GO'),
  ('ACLAEM',1880,'Tres Marias - MG'),
  ('ACLAGA',314,'Araguaina - TO'),
  ('ACLAGP',325,'Alto Alegre do Pindare - MA'),
  ('ACLALG',1759,'Alagoinhas - BA'),
  ('ACLAME',2828,'Ampere - PR'),
  ('ACLANN',496,'Ananindeua - PA'),
  ('ACLANP',1418,'Anapolis - GO'),
  ('ACLAPG',1491,'Aparecida de Goiania - GO'),
  ('ACLAPR',1756,'Arapiraca - AL'),
  ('ACLAQQ',2863,'Araquari - SC'),
  ('ACLARJ',2402,'Aruja - SP'),
  ('ACLARQ',2097,'Araraquara - SP'),
  ('ACLARR',2701,'Araucaria - PR'),
  ('ACLARU',1670,'Caruaru - PE'),
  ('ACLASS',1186,'Assare - CE'),
  ('ACLATI',2340,'Atibaia - SP'),
  ('ACLAXA',2004,'Araxa - MG'),
  ('ACLBAE',1524,'Seabra - BA'),
  ('ACLBAI',1130,'Barreiras - BA'),
  ('ACLBAL',456,'Balsas - MA'),
  ('ACLBAX',1819,'Bayeux - PB'),
  ('ACLBBD',376,'Barra do Corda - MA'),
  ('ACLBBR',2288,'Cambara - PR'),
  ('ACLBCA',504,'Barcarena - PA'),
  ('ACLBCN',3159,'Braco do Norte - SC'),
  ('ACLBDT',2919,'Braco do Trombudo - SC'),
  ('ACLBEH',2143,'Belo Horizonte - MG'),
  ('ACLBEM',504,'Belem - PA'),
  ('ACLBET',2152,'Betim - MG'),
  ('ACLBIB',2172,'Itabela - BA'),
  ('ACLBIR',2127,'Birigui - SP'),
  ('ACLBJL',97,'Bom Jesus das Selvas - MA'),
  ('ACLBJM',1619,'Belo Jardim - PE'),
  ('ACLBLU',2918,'Blumenau - SC'),
  ('ACLBMS',3264,'Bom Retiro do Sul - RS'),
  ('ACLBOI',2304,'Boituva - SP'),
  ('ACLBPB',1973,'Paranaiba - MS'),
  ('ACLBRA',1439,'Brasilia - DF'),
  ('ACLBRG',2342,'Braganca Paulista - SP'),
  ('ACLBRU',1690,'Brumado - BA'),
  ('ACLBSV',2687,'Balsa Nova - PR'),
  ('ACLBTU',1253,'Baturite - CE'),
  ('ACLBUU',2205,'Bauru - SP'),
  ('ACLBVE',3236,'Bento Goncalves - RS'),
  ('ACLCA7',2531,'Canas - SP'),
  ('ACLCAA',1870,'Caapora - PB'),
  ('ACLCAL',2680,'Campo Largo - PR'),
  ('ACLCAS',3176,'Caxias do Sul - RS'),
  ('ACLCBI',2425,'Cambui - MG'),
  ('ACLCCB',2931,'Camboriu - SC'),
  ('ACLCCC',2615,'Cariacica - ES'),
  ('ACLCET',2400,'Itaquaquecetuba - SP'),
  ('ACLCGD',1708,'Campina Grande - PB'),
  ('ACLCHA',600,'Chapadinha - MA'),
  ('ACLCHF',2233,'Conselheiro Lafaiete - MG'),
  ('ACLCII',2345,'Caieiras - SP'),
  ('ACLCJM',2337,'Cajamar - SP'),
  ('ACLCLA',2422,'Claudio - MG'),
  ('ACLCLP',2328,'Campo Limpo Paulista - SP'),
  ('ACLCLU',1649,'Cacule - BA'),
  ('ACLCMC',1806,'Camacari - BA'),
  ('ACLCMG',2318,'Campo Grande - MS'),
  ('ACLCMV',2008,'Curvelo - MG'),
  ('ACLCNN',1425,'Canarana - MT'),
  ('ACLCNS',3443,'Canoas - RS'),
  ('ACLCNV',1638,'Caldas Novas - GO'),
  ('ACLCOB',1126,'Campos Belos - GO'),
  ('ACLCOJ',1736,'Conceicao do Jacuipe - BA'),
  ('ACLCPB',2359,'Carapicuiba - SP'),
  ('ACLCPC',2988,'Chapeco - SC'),
  ('ACLCPG',1545,'Capim Grosso - BA'),
  ('ACLCPS',2276,'Campinas - SP'),
  ('ACLCRF',2291,'Coronel Fabriciano - MG'),
  ('ACLCRP',1804,'Carpina - PE'),
  ('ACLCRS',3624,'Cruzeiro do Sul - AC'),
  ('ACLCRT',2709,'Curitiba - PR'),
  ('ACLCSG',1808,'Cabo de Santo Agostinho - PE'),
  ('ACLCST',454,'Castanhal - PA'),
  ('ACLCTD',2046,'Catanduva - SP'),
  ('ACLCTG',2134,'Contagem - MG'),
  ('ACLCTS',2438,'Cataguases - MG'),
  ('ACLCUC',1249,'Caucaia - CE'),
  ('ACLCUZ',3226,'Cruz Alta - RS'),
  ('ACLCVI',2265,'Capivari - SP'),
  ('ACLCZA',1746,'Cruz das Almas - BA'),
  ('ACLDCO',1972,'Carmo do Paranaiba - MG'),
  ('ACLDDV',1812,'Dias d''Avila - BA'),
  ('ACLDEL',1569,'Delmiro Gouveia - AL'),
  ('ACLDGD',759,'Barao de Grajau - MA'),
  ('ACLDIA',2382,'Diadema - SP'),
  ('ACLDIV',2391,'Divinopolis - MG'),
  ('ACLDPB',2017,'Potirendaba - SP'),
  ('ACLDPT',2518,'Santo Antonio de Padua - RJ'),
  ('ACLDRA',2236,'Dracena - SP'),
  ('ACLDRD',2540,'Dourados - MS'),
  ('ACLDSA',2127,'Sao Jose da Lapa - MG'),
  ('ACLEEU',514,'Abaetetuba - PA'),
  ('ACLEGB',1494,'Santa Barbara de Goias - GO'),
  ('ACLEIT',191,'Estreito - MA'),
  ('ACLEOB',2226,'Borebi - SP'),
  ('ACLERE',2987,'Erechim - RS'),
  ('ACLERH',2240,'Engenheiro Coelho - SP'),
  ('ACLESC',1782,'Escada - PE'),
  ('ACLEUN',2145,'Eunapolis - BA'),
  ('ACLFCA',2055,'Franca - SP'),
  ('ACLFEO',1020,'Confresa - MT'),
  ('ACLFGR',1543,'Cristalina - GO'),
  ('ACLFLO',3007,'Florianopolis - SC'),
  ('ACLFMG',2317,'Formiga - MG'),
  ('ACLFND',2029,'Fernandopolis - SP'),
  ('ACLFOR',1273,'Fortaleza - CE'),
  ('ACLFRC',2879,'Francisco Beltrao - PR'),
  ('ACLFRG',2726,'Fazenda Rio Grande - PR'),
  ('ACLFRV',2400,'Ferraz de Vasconcelos - SP'),
  ('ACLFSD',2321,'Ipaussu - SP'),
  ('ACLFSN',1707,'Feira de Santana - BA'),
  ('ACLFTL',1888,'Frutal - MG'),
  ('ACLGAI',1465,'Antonio Goncalves - BA'),
  ('ACLGDO',96,'Governador Edison Lobao - MA'),
  ('ACLGIM',2858,'Guaramirim - SC'),
  ('ACLGMI',2807,'Guajara-Mirim - RO'),
  ('ACLGON',1477,'Goiania - GO'),
  ('ACLGPC',2016,'Guapiacu - SP'),
  ('ACLGRA',1717,'Gravata - PE'),
  ('ACLGRE',2423,'Guararema - SP'),
  ('ACLGRJ',978,'Granja - CE'),
  ('ACLGRP',843,'Gurupi - TO'),
  ('ACLGRV',2800,'Garuva - SC'),
  ('ACLGTA',3420,'Gravatai - RS'),
  ('ACLGUA',2378,'Guarulhos - SP'),
  ('ACLGUJ',2461,'Guaruja - SP'),
  ('ACLGUN',1582,'Guanambi - BA'),
  ('ACLGUT',2513,'Guaratingueta - SP'),
  ('ACLHHI',2251,'Piumhi - MG'),
  ('ACLHOZ',1308,'Horizonte - CE'),
  ('ACLHSM',2212,'Bom Despacho - MG'),
  ('ACLIAR',3177,'Icara - SC'),
  ('ACLIBE',1805,'Itambe - PE'),
  ('ACLIDI',2911,'Indaial - SC'),
  ('ACLIDS',2381,'Itapecerica da Serra - SP'),
  ('ACLIDT',2298,'Indaiatuba - SP'),
  ('ACLIED',2365,'Piedade - SP'),
  ('ACLIGU',1820,'Igarassu - PE'),
  ('ACLIIN',54,'Cidelandia - MA'),
  ('ACLIJA',2916,'Itajai - SC'),
  ('ACLIJU',3231,'Ijui - RS'),
  ('ACLIMG',2241,'Itabira - MG'),
  ('ACLIMP',68,'Imperatriz - MA'),
  ('ACLINL',2200,'Inubia Paulista - SP'),
  ('ACLINS',2109,'Lins - SP'),
  ('ACLINT',2941,'Itapema - SC'),
  ('ACLIPN',2350,'Itapetininga - SP'),
  ('ACLIPT',2278,'Ipatinga - MG'),
  ('ACLIPV',2307,'Itupeva - SP'),
  ('ACLIRA',2320,'Itapira - SP'),
  ('ACLIRM',2220,'Iracemapolis - SP'),
  ('ACLITN',2028,'Itabuna - BA'),
  ('ACLITO',1156,'Itapipoca - CE'),
  ('ACLITP',2946,'Ituporanga - SC'),
  ('ACLITT',2309,'Itatiba - SP'),
  ('ACLITV',2371,'Itapevi - SP'),
  ('ACLIZE',1966,'Buritizeiro - MG'),
  ('ACLJBE',1277,'Jaguaribe - CE'),
  ('ACLJBR',1802,'Jaboatao dos Guararapes - PE'),
  ('ACLJCB',1575,'Jacobina - BA'),
  ('ACLJDS',2858,'Jaragua do Sul - SC'),
  ('ACLJIP',2828,'Ji-Parana - RO'),
  ('ACLJNV',2559,'Joao Neiva - ES'),
  ('ACLJOI',2836,'Joinville - SC'),
  ('ACLJOL',74,'Joao Lisboa - MA'),
  ('ACLJOP',1745,'Joao Pinheiro - MG'),
  ('ACLJPA',1826,'Joao Pessoa - PB'),
  ('ACLJQI',2287,'Jumirim - SP'),
  ('ACLJRI',2415,'Jacarei - SP'),
  ('ACLJSE',3004,'Sao Jose - SC'),
  ('ACLJTI',1798,'Jatai - GO'),
  ('ACLJUA',1263,'Juazeiro do Norte - CE'),
  ('ACLJUD',2315,'Jundiai - SP'),
  ('ACLJUI',2393,'Juiz de Fora - MG'),
  ('ACLJUZ',1315,'Juazeiro - BA'),
  ('ACLKFJ',1748,'Aramari - BA'),
  ('ACLLAG',2959,'Lages - SC'),
  ('ACLLAR',1759,'Lagarto - SE'),
  ('ACLLDE',1799,'Sao Lourenco da Mata - PE'),
  ('ACLLDF',1817,'Lauro de Freitas - BA'),
  ('ACLLDS',450,'Campos Lindos - TO'),
  ('ACLLEV',2250,'Joao Monlevade - MG'),
  ('ACLLGA',3110,'Laguna - SC'),
  ('ACLLIA',1736,'Amelia Rodrigues - BA'),
  ('ACLLIM',1356,'Limoeiro do Norte - CE'),
  ('ACLLIN',2531,'Linhares - ES'),
  ('ACLLIR',2223,'Limeira - SP'),
  ('ACLLMA',1557,'Palmeiras - BA'),
  ('ACLLMO',1753,'Limoeiro - PE'),
  ('ACLLOD',2388,'Londrina - PR'),
  ('ACLLPI',716,'Lagoa do Piaui - PI'),
  ('ACLLRP',2283,'Laranjal Paulista - SP'),
  ('ACLMAB',237,'Maraba - PA'),
  ('ACLMAC',1269,'Maracanau - CE'),
  ('ACLMAO',2070,'Matao - SP'),
  ('ACLMAP',1271,'Maranguape - CE'),
  ('ACLMCB',1846,'Macaiba - RN'),
  ('ACLMCZ',2421,'Mogi das Cruzes - SP'),
  ('ACLMDE',77,'Dom Eliseu - PA'),
  ('ACLMDH',172,'Amarante do Maranhao - MA'),
  ('ACLMEO',1809,'Maceio - AL'),
  ('ACLMGC',2301,'Mogi Guacu - SP'),
  ('ACLMIN',427,'Miranda do Norte - MA'),
  ('ACLMJZ',2421,'Mogi das Cruzes - SP'),
  ('ACLMML',2887,'Marmeleiro - PR'),
  ('ACLMNR',2277,'Monte Mor - SP'),
  ('ACLMNU',1434,'Inhumas - GO'),
  ('ACLMOR',1776,'Moreno - PE'),
  ('ACLMOS',1500,'Mossoro - RN'),
  ('ACLMRA',1108,'Marco - CE'),
  ('ACLMRG',2429,'Maringa - PR'),
  ('ACLMRJ',2476,'Maracaju - MS'),
  ('ACLMSC',1814,'Monte Carmelo - MG'),
  ('ACLMSP',1049,'Massape - CE'),
  ('ACLMTC',1794,'Montes Claros - MG'),
  ('ACLMUA',2394,'Maua - SP'),
  ('ACLMUS',2966,'Manaus - AM'),
  ('ACLNAT',1866,'Natal - RN'),
  ('ACLNAU',1658,'Janauba - MG'),
  ('ACLNDD',1481,'Senador Canedo - GO'),
  ('ACLNDP',414,'Santa Maria do Para - PA'),
  ('ACLNFH',3200,'Forquilhinha - SC'),
  ('ACLNFO',2120,'Confins - MG'),
  ('ACLNGT',119,'Itaguatins - TO'),
  ('ACLNMS',2587,'Navirai - MS'),
  ('ACLNNO',84,'Davinopolis - MA'),
  ('ACLNOH',3347,'Novo Hamburgo - RS'),
  ('ACLNOO',2253,'Nova Odessa - SP'),
  ('ACLNOS',2239,'Nova Serrana - MG'),
  ('ACLNOV',2164,'Nova Lima - MG'),
  ('ACLNSL',1695,'Nossa Senhora da Gloria - SE'),
  ('ACLOBE',1811,'Taiobeiras - MG'),
  ('ACLOEI',875,'Oeiras - PI'),
  ('ACLOFP',167,'Porto Franco - MA'),
  ('ACLOHC',3049,'Coxilha - RS'),
  ('ACLOHN',1784,'Nossa Senhora do Socorro - SE'),
  ('ACLOKD',2255,'Panorama - SP'),
  ('ACLOLI',1807,'Olinda - PE'),
  ('ACLONS',1486,'Sao Luis de Montes Belos - GO'),
  ('ACLOOI',674,'Timon - MA'),
  ('ACLOPF',561,'Pedro Afonso - TO'),
  ('ACLORL',2050,'Orlandia - SP'),
  ('ACLOSO',3345,'Osorio - RS'),
  ('ACLOTI',2377,'Cotia - SP'),
  ('ACLOUR',2266,'Ourinhos - SP'),
  ('ACLPAM',1859,'Parnamirim - RN'),
  ('ACLPBI',2710,'Paracambi - RJ'),
  ('ACLPCC',2231,'Piracicaba - SP'),
  ('ACLPCD',2300,'Pocos de Caldas - MG'),
  ('ACLPCS',987,'Picos - PI'),
  ('ACLPEE',2344,'Pedreira - SP'),
  ('ACLPGN',237,'Paragominas - PA'),
  ('ACLPGT',1044,'Porangatu - GO'),
  ('ACLPHN',2482,'Pindamonhangaba - SP'),
  ('ACLPID',472,'Presidente Dutra - MA'),
  ('ACLPIH',2719,'Pinhais - PR'),
  ('ACLPIM',1927,'Patos de Minas - MG'),
  ('ACLPJG',2482,'Pindamonhangaba - SP'),
  ('ACLPLA',1315,'Petrolina - PE'),
  ('ACLPLF',1552,'Paulo Afonso - BA'),
  ('ACLPLL',2112,'Pedro Leopoldo - MG'),
  ('ACLPLM',688,'Palmas - TO'),
  ('ACLPLP',1433,'Lapao - BA'),
  ('ACLPLT',1814,'Paulista - PE'),
  ('ACLPLW',1766,'Pilar - AL'),
  ('ACLPMN',2285,'Para de Minas - MG'),
  ('ACLPNI',2267,'Paulinia - SP'),
  ('ACLPNS',2187,'Pederneiras - SP'),
  ('ACLPOA',2402,'Poa - SP'),
  ('ACLPOP',2658,'Ponta Pora - MS'),
  ('ACLPOU',2403,'Pouso Alegre - MG'),
  ('ACLPRN',2448,'Paranavai - PR'),
  ('ACLPRP',2260,'Presidente Prudente - SP'),
  ('ACLPRT',668,'Paraiso do Tocantins - TO'),
  ('ACLPRV',2484,'Porto Velho - RO'),
  ('ACLPSF',3066,'Passo Fundo - RS'),
  ('ACLPTC',1906,'Patrocinio - MG'),
  ('ACLPTG',2592,'Ponta Grossa - PR'),
  ('ACLPTO',1574,'Patos - PB'),
  ('ACLPTS',2207,'Porto Seguro - BA'),
  ('ACLPVL',1894,'Primavera do Leste - MT'),
  ('ACLQXE',1369,'Quixere - CE'),
  ('ACLQYZ',1634,'Garanhuns - PE'),
  ('ACLRBP',2402,'Ribeirao Pires - SP'),
  ('ACLRCI',154,'Buriticupu - MA'),
  ('ACLREC',1799,'Recife - PE'),
  ('ACLREN',2893,'Renascenca - PR'),
  ('ACLRFN',1442,'Senhor do Bonfim - BA'),
  ('ACLRGT',2531,'Registro - SP'),
  ('ACLRII',1718,'Paripiranga - BA'),
  ('ACLRIS',2921,'Rio do Sul - SC'),
  ('ACLRJN',2778,'Rio de Janeiro - RJ'),
  ('ACLRNO',1997,'Rondonopolis - MT'),
  ('ACLROD',2924,'Rodeio - SC'),
  ('ACLROL',2747,'Rolim de Moura - RO'),
  ('ACLRPO',2065,'Ribeirao Preto - SP'),
  ('ACLRTA',1725,'Aracatu - BA'),
  ('ACLRUR',1081,'Ruropolis - PA'),
  ('ACLRVD',1709,'Rio Verde - GO'),
  ('ACLSAV',1822,'Salvador - BA'),
  ('ACLSBC',2390,'Sao Bernardo do Campo - SP'),
  ('ACLSBV',2273,'Sao Joao da Boa Vista - SP'),
  ('ACLSCA',2305,'Santa Cruz do Rio Pardo - SP'),
  ('ACLSCQ',2946,'Brusque - SC'),
  ('ACLSCS',2429,'Sao Jose dos Campos - SP'),
  ('ACLSGM',1730,'Sao Goncalo dos Campos - BA'),
  ('ACLSHA',1388,'Serra Talhada - PE'),
  ('ACLSHS',1561,'Sao Jose do Jacuipe - BA'),
  ('ACLSID',3200,'Sideropolis - SC'),
  ('ACLSII',1717,'Sorriso - MT'),
  ('ACLSIN',1597,'Sinop - MT'),
  ('ACLSJI',2727,'Sao Jose dos Pinhais - PR'),
  ('ACLSLU',563,'Sao Luis - MA'),
  ('ACLSMF',1796,'Simoes Filho - BA'),
  ('ACLSMM',382,'Sao Miguel do Guama - PA'),
  ('ACLSNN',2351,'Serra Negra - SP'),
  ('ACLSNP',2349,'Santana de Parnaiba - SP'),
  ('ACLSOB',1041,'Sobral - CE'),
  ('ACLSOC',2333,'Sorocaba - SP'),
  ('ACLSOO',1991,'Sao Jose do Rio Preto - SP'),
  ('ACLSPO',2368,'Sao Paulo - SP'),
  ('ACLSPZ',2254,'Sapezal - MT'),
  ('ACLSQB',2036,'Sao Joaquim da Barra - SP'),
  ('ACLSRP',2428,'Santa Rita do Sapucai - MG'),
  ('ACLSRR',2612,'Serra - ES'),
  ('ACLSTJ',1785,'Santo Antonio de Jesus - BA'),
  ('ACLSTN',316,'Santa Ines - MA'),
  ('ACLSTO',991,'Sao Benedito - CE'),
  ('ACLSUJ',668,'Sao Joao dos Patos - MA'),
  ('ACLSUR',2259,'Sumare - SP'),
  ('ACLSUZ',2410,'Suzano - SP'),
  ('ACLSWW',2079,'Sete Lagoas - MG'),
  ('ACLSZP',482,'Santa Izabel do Para - PA'),
  ('ACLSZS',2814,'Santa Izabel do Oeste - PR'),
  ('ACLTAH',2608,'Cachoeiro de Itapemirim - ES'),
  ('ACLTAS',2407,'Tres Coracoes - MG'),
  ('ACLTAT',2310,'Tatui - SP'),
  ('ACLTBA',1720,'Itaberaba - BA'),
  ('ACLTBB',1847,'Timbauba - PE'),
  ('ACLTBC',2918,'Trombudo Central - SC'),
  ('ACLTBT',2465,'Taubate - SP'),
  ('ACLTDG',1479,'Guaranta do Norte - MT'),
  ('ACLTEI',2306,'Teixeira de Freitas - BA'),
  ('ACLTHA',58,'Itinga do Maranhao - MA'),
  ('ACLTHE',683,'Teresina - PI'),
  ('ACLTIA',956,'Tiangua - CE'),
  ('ACLTIJ',2958,'Tijucas - SC'),
  ('ACLTIO',2457,'Tres Rios - RJ'),
  ('ACLTJB',2469,'Itajuba - MG'),
  ('ACLTLN',1342,'Tabuleiro do Norte - CE'),
  ('ACLTLR',2149,'Tres Lagoas - MS'),
  ('ACLTOA',2275,'Santana do Paraiso - MG'),
  ('ACLTOC',2401,'Tocantins - MG'),
  ('ACLTOM',432,'Tome-Acu - PA'),
  ('ACLTPL',2632,'Prudentopolis - PR'),
  ('ACLTRE',2473,'Tremembe - SP'),
  ('ACLTSG',597,'Tasso Fragoso - MA'),
  ('ACLTTO',2299,'Timoteo - MG'),
  ('ACLTTT',2196,'Itatiaiucu - MG'),
  ('ACLTUB',3128,'Tubarao - SC'),
  ('ACLTUC',665,'Tucuma - PA'),
  ('ACLUBE',1826,'Uberlandia - MG'),
  ('ACLUBI',1880,'Ubaira - BA'),
  ('ACLUBJ',967,'Ubajara - CE'),
  ('ACLUBR',1934,'Uberaba - MG'),
  ('ACLUBT',2562,'Ubatuba - SP'),
  ('ACLUFF',1471,'Luziania - GO'),
  ('ACLUGM',2345,'Aracariguama - SP'),
  ('ACLUKF',742,'Altamira - PA'),
  ('ACLUMR',2590,'Umuarama - PR'),
  ('ACLUPE',398,'Parauapebas - PA'),
  ('ACLUSI',1283,'Eusebio - CE'),
  ('ACLUTI',2301,'Itu - SP'),
  ('ACLVGL',2253,'Vargem Grande do Sul - SP'),
  ('ACLVIH',2295,'Vinhedo - SP'),
  ('ACLVIL',2637,'Vila Velha - ES'),
  ('ACLVIN',2377,'Varginha - MG'),
  ('ACLVLI',886,'Valenca do Piaui - PI'),
  ('ACLVOD',93,'Sitio Novo do Tocantins - TO'),
  ('ACLVRL',3190,'Vila Flores - RS'),
  ('ACLVSN',1749,'Vitoria de Santo Antao - PE'),
  ('ACLVTC',1826,'Vitoria da Conquista - BA'),
  ('ACLVZG',2132,'Varzea Grande - MT'),
  ('ACLVZP',2323,'Varzea Paulista - SP')
) AS v(codigo, km, res) WHERE t.codigo = v.codigo;

-- DUVIDAS (32): cidade homonima sem criterio para decidir. O Yves vai conferir no CTe
-- de quais delas ha movimento; as demais nunca rodaram carga.
--   ACLABN  SANTA ISABEL           ambiguo: Santa Isabel/SP, Santa Isabel/GO
--   ACLAIV  VIANA                  ambiguo: Viana/MA, Viana/ES
--   ACLBRB  BARRA BONITA           ambiguo: Barra Bonita/SP, Barra Bonita/SC
--   ACLBVS  BOA VISTA              ambiguo: Boa Vista/RR, Boa Vista/PB
--   ACLCAF  CAFELANDIA             ambiguo: Cafelandia/SP, Cafelandia/PR
--   ACLCHN  CACHOEIRINHA           ambiguo: Cachoeirinha/TO, Cachoeirinha/PE, Cachoeirinha/RS
--   ACLCVL  CASCAVEL               ambiguo: Cascavel/CE, Cascavel/PR
--   ACLFLD  FILADELFIA             ambiguo: Filadelfia/TO, Filadelfia/BA
--   ACLGML  CAMPO ALEGRE           ambiguo: Campo Alegre/AL, Campo Alegre/SC
--   ACLGOE  GOIANESIA              Goianesia: TMS 2.000 km; existe Goianesia/GO e Goianesia do Para/PA
--   ACLGOM  GOIANESIA              Goianesia: TMS 1.458 km; mesmo nome do ACLGOE, provavelmente a outra
--   ACLIQU  ITAQUERA               sem municipio com esse nome
--   ACLITB  ITABAIANA              ambiguo: Itabaiana/PB, Itabaiana/SE
--   ACLJCT  JACUTINGA              ambiguo: Jacutinga/MG, Jacutinga/RS
--   ACLLAJ  LAJEADO                ambiguo: Lajeado/TO, Lajeado/RS
--   ACLLST  LAGOA SANTA            ambiguo: Lagoa Santa/MG, Lagoa Santa/GO
--   ACLMNB  CANDEIAS               ambiguo: Candeias/BA, Candeias/MG
--   ACLNVZ  NOVA VENEZA            ambiguo: Nova Veneza/SC, Nova Veneza/GO
--   ACLPRG  PRAIA GRANDE           ambiguo: Praia Grande/SP, Praia Grande/SC
--   ACLRIC  RIO CLARO              ambiguo: Rio Claro/RJ, Rio Claro/SP
--   ACLRNA  REDENCAO               Redencao: TMS 1.220 km sugere CE, o calculo usou PA (581)
--   ACLSAB  SAO BENTO              Sao Bento: TMS 486 km sugere MA, o calculo usou PB (1.564)
--   ACLSAE  SANTO ANDRE            ambiguo: Santo Andre/PB, Santo Andre/SP
--   ACLSAN  SANTANA                Santana: TMS 1.042 km, calculo usou Santana/AP (1.876)
--   ACLSBT  SAO JOAO BATISTA       ambiguo: Sao Joao Batista/MA, Sao Joao Batista/SC
--   ACLSCL  SAO CARLOS             ambiguo: Sao Carlos/SP, Sao Carlos/SC
--   ACLSSB  SAO SEBASTIAO          ambiguo: Sao Sebastiao/AL, Sao Sebastiao/SP
--   ACLTDD  TRINDADE               ambiguo: Trindade/PE, Trindade/GO
--   ACLTOL  TOLEDO                 ambiguo: Toledo/MG, Toledo/PR
--   ACLUOA  AURORA                 ambiguo: Aurora/CE, Aurora/SC
--   ACLVIS  VICOSA                 ambiguo: Vicosa/RN, Vicosa/AL, Vicosa/MG
--   ACLVLA  VALENCA                ambiguo: Valenca/BA, Valenca/RJ
